
$ontext
Example update file demonstrating the use of S space and the pGen file
$offtext

pGen('wind','cap_cur',S)=4.71500;
pGen('old_coal_lig_st','cap_cur',S)=4.37297;
pGen('old_coal_sub_st','cap_cur',S)=4.23962;
pGen('old_ng_cc','cap_cur',S)=11.52047;
pGen('old_ng_gt','cap_cur',S)=2.05218;
pGen('old_ng_st','cap_cur',S)=11.44558;
pGen('old_nuke_st','cap_cur',S)=2.56930;
pGen('new_coal_st','cap_cur',S)=0.00000;
pGen('new_ng_cc','cap_cur',S)=6.00000;
pGen('new_ng_gt_aero','cap_cur',S)=6.93000;
pGen('new_nuke_st','cap_cur',S)=22.36000;
pGen('new_coal_st_ccs','cap_cur',S)=0.00000;
pGen('new_ng_cc_ccs','cap_cur',S)=0.38500;
